/* 1. 중요정보 카드 - Chart SQL */
WITH WT_WHERE AS
    (
        SELECT STATISTICS_DATE - INTERVAL '1 MONTH' AS FR_DT
              ,STATISTICS_DATE                      AS TO_DT
              ,DATE_TRUNC('YEAR', STATISTICS_DATE)  AS FR_DT_YEAR
          FROM DASH.{TAG}_PRICEANALYSISCARD
    ), WT_BASE AS
    (
        SELECT 'MNTH'            AS CHRT_KEY
              ,STATISTICS_DATE   AS X_DT
              ,AV_SALE_PRICE_RMB AS Y_VAL_RMB
              ,AV_SALE_PRICE_KRW AS Y_VAL_KRW
          FROM DASH.{TAG}_PRICETIMESERIESCHART
         WHERE STATISTICS_DATE BETWEEN (SELECT FR_DT FROM WT_WHERE) AND (SELECT TO_DT FROM WT_WHERE)
     UNION ALL
        SELECT 'YTD Total'             AS CHRT_KEY
              ,STATISTICS_DATE   AS X_DT
              ,AV_SALE_PRICE_RMB AS Y_VAL_RMB
              ,AV_SALE_PRICE_KRW AS Y_VAL_KRW
          FROM DASH.{TAG}_PRICETIMESERIESCHART
         WHERE STATISTICS_DATE BETWEEN (SELECT FR_DT_YEAR FROM WT_WHERE) AND (SELECT TO_DT FROM WT_WHERE)
    )
    SELECT CHRT_KEY   /* MNTH:한달 평균, YTD Total:YTD Total 평균 */
          ,CAST(X_DT AS DATE)      AS X_DT
          ,COALESCE(CAST(Y_VAL_RMB AS DECIMAL(20,2)), 0) AS Y_VAL_RMB
          ,COALESCE(CAST(Y_VAL_KRW AS DECIMAL(20,2)), 0) AS Y_VAL_KRW
      FROM WT_BASE
  ORDER BY CHRT_KEY
          ,X_DT