/* 4. 방문자 분포 그래프 그래프 - 하단표 SQL */
WITH WT_WHERE AS
    (
        SELECT FRST_DT_YEAR             AS FR_DT      /* 기준일의  1월  1일       */
              ,BASE_YEAR    ||'-12-31'  AS TO_DT      /* 기준일의 12월 31일       */
          FROM DASH.DASH_INITIAL_DATE
    ), WT_COPY AS
    (
        SELECT 1                        AS SORT_KEY
              ,'방문자 중 첫 방문자 비중' AS ROW_TITL
     UNION ALL
        SELECT 2        AS SORT_KEY
              ,'방문자 중 구매자 비중'    AS ROW_TITL
    ), WT_CAST AS
    (
        SELECT STATISTICS_DATE
              ,NUMBER_OF_VISITORS    AS VIST_CNT  /* 방문자수   */
              ,NEW_VISITORS          AS FRST_CNT  /* 첫방문자수 */
              ,NUMBER_OF_PAID_BUYERS AS PAID_CNT  /* 구매자수   */
          FROM DASH_RAW.OVER_{TAG}_OVERALL_STORE A
         WHERE STATISTICS_DATE BETWEEN (SELECT FR_DT FROM WT_WHERE) AND (SELECT TO_DT FROM WT_WHERE)
    ), WT_SUM AS
    (
        SELECT TO_CHAR(CAST(STATISTICS_DATE AS DATE), 'MM') AS COL_MNTH
              ,SUM(VIST_CNT)                                AS VIST_CNT  /* 방문자수   */
              ,SUM(FRST_CNT)                                AS FRST_CNT  /* 첫방문자수 */
              ,SUM(PAID_CNT)                                AS PAID_CNT  /* 구매자수   */
          FROM WT_CAST A
      GROUP BY TO_CHAR(CAST(STATISTICS_DATE AS DATE), 'MM')
    ), WT_RATE AS
    (
        SELECT COL_MNTH       /* 월       */
              ,VIST_CNT       /* 방문자수 */
              ,CASE WHEN COALESCE(VIST_CNT, 0) = 0 THEN 0 ELSE FRST_CNT / VIST_CNT * 100 END AS FRST_RATE  /* 첫 방문자 비율 */
              ,CASE WHEN COALESCE(VIST_CNT, 0) = 0 THEN 0 ELSE PAID_CNT / VIST_CNT * 100 END AS PAID_RATE  /* 구매자    비율 */
          FROM WT_SUM A
    ), WT_BASE AS
    (
        SELECT SORT_KEY
              ,ROW_TITL
              ,SUM(CASE WHEN SORT_KEY = 1 AND COL_MNTH = '01' THEN FRST_RATE WHEN SORT_KEY = 2 AND COL_MNTH = '01' THEN PAID_RATE  END) AS COL_VAL_01
              ,SUM(CASE WHEN SORT_KEY = 1 AND COL_MNTH = '02' THEN FRST_RATE WHEN SORT_KEY = 2 AND COL_MNTH = '02' THEN PAID_RATE  END) AS COL_VAL_02
              ,SUM(CASE WHEN SORT_KEY = 1 AND COL_MNTH = '03' THEN FRST_RATE WHEN SORT_KEY = 2 AND COL_MNTH = '03' THEN PAID_RATE  END) AS COL_VAL_03
              ,SUM(CASE WHEN SORT_KEY = 1 AND COL_MNTH = '04' THEN FRST_RATE WHEN SORT_KEY = 2 AND COL_MNTH = '04' THEN PAID_RATE  END) AS COL_VAL_04
              ,SUM(CASE WHEN SORT_KEY = 1 AND COL_MNTH = '05' THEN FRST_RATE WHEN SORT_KEY = 2 AND COL_MNTH = '05' THEN PAID_RATE  END) AS COL_VAL_05
              ,SUM(CASE WHEN SORT_KEY = 1 AND COL_MNTH = '06' THEN FRST_RATE WHEN SORT_KEY = 2 AND COL_MNTH = '06' THEN PAID_RATE  END) AS COL_VAL_06
              ,SUM(CASE WHEN SORT_KEY = 1 AND COL_MNTH = '07' THEN FRST_RATE WHEN SORT_KEY = 2 AND COL_MNTH = '07' THEN PAID_RATE  END) AS COL_VAL_07
              ,SUM(CASE WHEN SORT_KEY = 1 AND COL_MNTH = '08' THEN FRST_RATE WHEN SORT_KEY = 2 AND COL_MNTH = '08' THEN PAID_RATE  END) AS COL_VAL_08
              ,SUM(CASE WHEN SORT_KEY = 1 AND COL_MNTH = '09' THEN FRST_RATE WHEN SORT_KEY = 2 AND COL_MNTH = '09' THEN PAID_RATE  END) AS COL_VAL_09
              ,SUM(CASE WHEN SORT_KEY = 1 AND COL_MNTH = '10' THEN FRST_RATE WHEN SORT_KEY = 2 AND COL_MNTH = '10' THEN PAID_RATE  END) AS COL_VAL_10
              ,SUM(CASE WHEN SORT_KEY = 1 AND COL_MNTH = '11' THEN FRST_RATE WHEN SORT_KEY = 2 AND COL_MNTH = '11' THEN PAID_RATE  END) AS COL_VAL_11
              ,SUM(CASE WHEN SORT_KEY = 1 AND COL_MNTH = '12' THEN FRST_RATE WHEN SORT_KEY = 2 AND COL_MNTH = '12' THEN PAID_RATE  END) AS COL_VAL_12
          FROM WT_COPY A 
              ,WT_RATE B
      GROUP BY SORT_KEY
              ,ROW_TITL
    )
    SELECT ROW_TITL
          ,TO_CHAR(CAST(COL_VAL_01 AS DECIMAL(20,2)), 'FM999,999,999,999,990.99%') AS COL_VAL_01
          ,TO_CHAR(CAST(COL_VAL_02 AS DECIMAL(20,2)), 'FM999,999,999,999,990.99%') AS COL_VAL_02
          ,TO_CHAR(CAST(COL_VAL_03 AS DECIMAL(20,2)), 'FM999,999,999,999,990.99%') AS COL_VAL_03
          ,TO_CHAR(CAST(COL_VAL_04 AS DECIMAL(20,2)), 'FM999,999,999,999,990.99%') AS COL_VAL_04
          ,TO_CHAR(CAST(COL_VAL_05 AS DECIMAL(20,2)), 'FM999,999,999,999,990.99%') AS COL_VAL_05
          ,TO_CHAR(CAST(COL_VAL_06 AS DECIMAL(20,2)), 'FM999,999,999,999,990.99%') AS COL_VAL_06
          ,TO_CHAR(CAST(COL_VAL_07 AS DECIMAL(20,2)), 'FM999,999,999,999,990.99%') AS COL_VAL_07
          ,TO_CHAR(CAST(COL_VAL_08 AS DECIMAL(20,2)), 'FM999,999,999,999,990.99%') AS COL_VAL_08
          ,TO_CHAR(CAST(COL_VAL_09 AS DECIMAL(20,2)), 'FM999,999,999,999,990.99%') AS COL_VAL_09
          ,TO_CHAR(CAST(COL_VAL_10 AS DECIMAL(20,2)), 'FM999,999,999,999,990.99%') AS COL_VAL_10
          ,TO_CHAR(CAST(COL_VAL_11 AS DECIMAL(20,2)), 'FM999,999,999,999,990.99%') AS COL_VAL_11
          ,TO_CHAR(CAST(COL_VAL_12 AS DECIMAL(20,2)), 'FM999,999,999,999,990.99%') AS COL_VAL_12
      FROM WT_BASE
  ORDER BY SORT_KEY
