/* 라이브 아이디 선택 */ 
WITH WT_WHERE AS
    (
        SELECT {FR_DT} AS FR_DT  /* 사용자가 선택한 기간 - 시작일  ex) '2023-02-01'  */
              ,{TO_DT} AS TO_DT  /* 사용자가 선택한 기간 - 종료일  ex) '2023-02-13'  */
    ), WT_PROD AS
    (
        SELECT DISTINCT
               CAST(DOUYIN_ID AS VARCHAR) AS PRODUCT_ID
               ,CAST(EXPERT_NICKNAME AS VARCHAR) AS PRODUCT_NAME
          FROM DASH_RAW.OVER_{TAG}_SHOPPING_RECOMMEND_LIVE_DETAILS A
         WHERE DATE BETWEEN (SELECT CAST(CAST(FR_DT AS TEXT) AS DATE)  FROM WT_WHERE) AND (SELECT CAST(CAST(TO_DT AS TEXT) AS DATE) FROM WT_WHERE) 
    )
    SELECT PRODUCT_ID   AS PROD_ID
          ,PRODUCT_NAME AS PROD_NM
      FROM WT_PROD
  ORDER BY PRODUCT_NAME COLLATE "ko_KR.utf8"