/* 3. 전월 대비 긍정/부정 비율 변화 - 표 SQL */
WITH WT_WHERE AS
    (
        SELECT CAST(DATE_TRUNC('MONTH', CAST(BASE_DT AS DATE) - INTERVAL '1' MONTH)                              AS DATE) AS FR_DT      /* 오늘기준 -1개월  1일 ex) '2023-02-01' */
              ,CAST(DATE_TRUNC('MONTH', CAST(BASE_DT AS DATE) - INTERVAL '1' MONTH) + INTERVAL '1 MONTH - 1 DAY' AS DATE) AS TO_DT      /* 오늘기준 -1개월 말일 ex) '2023-02-28' */
              ,CAST(DATE_TRUNC('MONTH', CAST(BASE_DT AS DATE) - INTERVAL '2' MONTH)                              AS DATE) AS FR_DT_MOM  /* 오늘기준 -2개월  1일 ex) '2023-01-01' */
              ,CAST(DATE_TRUNC('MONTH', CAST(BASE_DT AS DATE) - INTERVAL '2' MONTH) + INTERVAL '1 MONTH - 1 DAY' AS DATE) AS TO_DT_MOM  /* 오늘기준 -2개월 말일 ex) '2023-01-31' */
              ,COALESCE({PSNG_TYPE}, 'PSTV')                                                                              AS PSNG_TYPE  /* 긍/부정 선택 (PSTV:긍정, NGTV:부정) ex) PGTV  */
          FROM REVIEW.REVIEW_INITIAL_DATE
    ), WT_CHNL AS
    (
        SELECT 0                AS SORT_KEY
              ,'ALL'            AS CHNL_ID
              ,'전체 채널'      AS CHNL_NM
     UNION ALL
        SELECT 1                AS SORT_KEY
              ,'DCT'            AS CHNL_ID
              ,'Tmall 내륙'     AS CHNL_NM
     UNION ALL
        SELECT 2                AS SORT_KEY
              ,'DGT'            AS CHNL_ID
              ,'Tmall 글로벌'   AS CHNL_NM
     UNION ALL
        SELECT 3                AS SORT_KEY
              ,'DCD'            AS CHNL_ID
              ,'Douyin 내륙'    AS CHNL_NM
     UNION ALL
        SELECT 4                AS SORT_KEY
              ,'DGD'            AS CHNL_ID
              ,'Douyin 글로벌'  AS CHNL_NM
    ), WT_COPY AS
    (
        SELECT 1 AS REVW_RANK
     UNION ALL
        SELECT 2 AS REVW_RANK
     UNION ALL
        SELECT 3 AS REVW_RANK
     UNION ALL
        SELECT 4 AS REVW_RANK
     UNION ALL
        SELECT 5 AS REVW_RANK
    ), WT_COPY_CHNL AS
    (
        SELECT SORT_KEY
              ,CHNL_ID
              ,CHNL_NM
              ,REVW_RANK
          FROM WT_CHNL A
              ,WT_COPY B
    ), WT_PROD AS
    (
        SELECT 'DCT' AS CHNL_ID
              ,BRAND
              ,REVIEW_RAW.SF_TMALL_PROD_NM(PROD_ID) AS PROD_NAME
              ,REVIEW_ID
              ,DATE
          FROM REVIEW_RAW.OVER_DCT_BASE_TABLE A
         WHERE DATE BETWEEN (SELECT FR_DT FROM WT_WHERE) AND (SELECT TO_DT FROM WT_WHERE)
     UNION ALL 
        SELECT 'DGT' AS CHNL_ID
              ,BRAND
              ,REVIEW_RAW.SF_TMALL_PROD_NM(PROD_ID) AS PROD_NAME
              ,REVIEW_ID
              ,DATE
          FROM REVIEW_RAW.OVER_DGT_BASE_TABLE A
         WHERE DATE BETWEEN (SELECT FR_DT FROM WT_WHERE) AND (SELECT TO_DT FROM WT_WHERE)
     UNION ALL 
        SELECT 'DCD' AS CHNL_ID
              ,BRAND
              ,REVIEW_RAW.SF_DOUYIN_PROD_NM(PROD_ID) AS PROD_NAME
              ,REVIEW_ID
              ,DATE
          FROM REVIEW_RAW.OVER_DCD_BASE_TABLE A
         WHERE DATE BETWEEN (SELECT FR_DT FROM WT_WHERE) AND (SELECT TO_DT FROM WT_WHERE)
     UNION ALL 
        SELECT 'DGD' AS CHNL_ID
              ,BRAND
              ,REVIEW_RAW.SF_DOUYIN_PROD_NM(PROD_ID) AS PROD_NAME
              ,REVIEW_ID
              ,DATE
          FROM REVIEW_RAW.OVER_DGD_BASE_TABLE A
         WHERE DATE BETWEEN (SELECT FR_DT FROM WT_WHERE) AND (SELECT TO_DT FROM WT_WHERE)
    ), WT_PROD_MOM AS
    (
        SELECT 'DCT' AS CHNL_ID
              ,BRAND
              ,REVIEW_RAW.SF_TMALL_PROD_NM(PROD_ID) AS PROD_NAME
              ,REVIEW_ID
              ,DATE
          FROM REVIEW_RAW.OVER_DCT_BASE_TABLE A
         WHERE DATE BETWEEN (SELECT FR_DT_MOM FROM WT_WHERE) AND (SELECT TO_DT_MOM FROM WT_WHERE)
     UNION ALL 
        SELECT 'DGT' AS CHNL_ID
              ,BRAND
              ,REVIEW_RAW.SF_TMALL_PROD_NM(PROD_ID) AS PROD_NAME
              ,REVIEW_ID
              ,DATE
          FROM REVIEW_RAW.OVER_DGT_BASE_TABLE A
         WHERE DATE BETWEEN (SELECT FR_DT_MOM FROM WT_WHERE) AND (SELECT TO_DT_MOM FROM WT_WHERE)
     UNION ALL 
        SELECT 'DCD' AS CHNL_ID
              ,BRAND
              ,REVIEW_RAW.SF_DOUYIN_PROD_NM(PROD_ID) AS PROD_NAME
              ,REVIEW_ID
              ,DATE
          FROM REVIEW_RAW.OVER_DCD_BASE_TABLE A
         WHERE DATE BETWEEN (SELECT FR_DT_MOM FROM WT_WHERE) AND (SELECT TO_DT_MOM FROM WT_WHERE)
     UNION ALL 
        SELECT 'DGD' AS CHNL_ID
              ,BRAND
              ,REVIEW_RAW.SF_DOUYIN_PROD_NM(PROD_ID) AS PROD_NAME
              ,REVIEW_ID
              ,DATE
          FROM REVIEW_RAW.OVER_DGD_BASE_TABLE A
         WHERE DATE BETWEEN (SELECT FR_DT_MOM FROM WT_WHERE) AND (SELECT TO_DT_MOM FROM WT_WHERE)
    ), WT_REVW_SUM AS
    (
        SELECT A.CHNL_ID
              ,B.PROD_NAME AS PROD_NM
              ,CAST(COUNT(*)                                          AS DECIMAL(20,2)) AS REVW_CNT
              ,CAST(COUNT(CASE WHEN SENT_RATING IN (4, 5) THEN 1 END) AS DECIMAL(20,2)) AS PSTV_CNT
              ,CAST(COUNT(CASE WHEN SENT_RATING IN (3   ) THEN 1 END) AS DECIMAL(20,2)) AS NTRL_CNT
              ,CAST(COUNT(CASE WHEN SENT_RATING IN (1, 2) THEN 1 END) AS DECIMAL(20,2)) AS NGTV_CNT
          FROM (
                    SELECT 'DCT' AS CHNL_ID, A.*
                      FROM REVIEW_RAW.OVER_DCT_REVIEW_SENTENCE_TABLE A INNER JOIN REVIEW_RAW.OVER_DCT_REVIEW_ABNORMAL F
                        ON (A.PROD_ID = F.PROD_ID AND A.DATE = F.DATE AND A.REVIEW_ID = F.REVIEW_ID AND F.FAKE = 0)
                     WHERE A.DATE BETWEEN (SELECT FR_DT FROM WT_WHERE) AND (SELECT TO_DT FROM WT_WHERE)
                 UNION ALL 
                    SELECT 'DGT' AS CHNL_ID, A.*
                      FROM REVIEW_RAW.OVER_DGT_REVIEW_SENTENCE_TABLE A INNER JOIN REVIEW_RAW.OVER_DGT_REVIEW_ABNORMAL F
                        ON (A.PROD_ID = F.PROD_ID AND A.DATE = F.DATE AND A.REVIEW_ID = F.REVIEW_ID AND F.FAKE = 0)
                     WHERE A.DATE BETWEEN (SELECT FR_DT FROM WT_WHERE) AND (SELECT TO_DT FROM WT_WHERE)
                 UNION ALL 
                    SELECT 'DCD' AS CHNL_ID, A.*
                      FROM REVIEW_RAW.OVER_DCD_REVIEW_SENTENCE_TABLE A INNER JOIN REVIEW_RAW.OVER_DCD_REVIEW_ABNORMAL F
                        ON (A.PROD_ID = F.PROD_ID AND A.DATE = F.DATE AND A.REVIEW_ID = F.REVIEW_ID AND F.FAKE = 0)
                     WHERE A.DATE BETWEEN (SELECT FR_DT FROM WT_WHERE) AND (SELECT TO_DT FROM WT_WHERE)
                 UNION ALL 
                    SELECT 'DGD' AS CHNL_ID, A.*
                      FROM REVIEW_RAW.OVER_DGD_REVIEW_SENTENCE_TABLE A INNER JOIN REVIEW_RAW.OVER_DGD_REVIEW_ABNORMAL F
                        ON (A.PROD_ID = F.PROD_ID AND A.DATE = F.DATE AND A.REVIEW_ID = F.REVIEW_ID AND F.FAKE = 0)
                     WHERE A.DATE BETWEEN (SELECT FR_DT FROM WT_WHERE) AND (SELECT TO_DT FROM WT_WHERE)
               ) A LEFT OUTER JOIN 
               WT_PROD B
            ON (A.CHNL_ID = B.CHNL_ID AND A.DATE = B.DATE AND A.REVIEW_ID = B.REVIEW_ID)
         WHERE B.BRAND = '더마펌'
      GROUP BY A.CHNL_ID
              ,B.PROD_NAME
        HAVING COUNT(*) > 100
    ), WT_REVW_SUM_MOM AS
    (
        SELECT A.CHNL_ID
              ,B.PROD_NAME AS PROD_NM
              ,CAST(COUNT(*)                                          AS DECIMAL(20,2)) AS REVW_CNT
              ,CAST(COUNT(CASE WHEN SENT_RATING IN (4, 5) THEN 1 END) AS DECIMAL(20,2)) AS PSTV_CNT
              ,CAST(COUNT(CASE WHEN SENT_RATING IN (3   ) THEN 1 END) AS DECIMAL(20,2)) AS NTRL_CNT
              ,CAST(COUNT(CASE WHEN SENT_RATING IN (1, 2) THEN 1 END) AS DECIMAL(20,2)) AS NGTV_CNT
          FROM (
                    SELECT 'DCT' AS CHNL_ID, A.*
                      FROM REVIEW_RAW.OVER_DCT_REVIEW_SENTENCE_TABLE A INNER JOIN REVIEW_RAW.OVER_DCT_REVIEW_ABNORMAL F
                        ON (A.PROD_ID = F.PROD_ID AND A.DATE = F.DATE AND A.REVIEW_ID = F.REVIEW_ID AND F.FAKE = 0)
                     WHERE A.DATE BETWEEN (SELECT FR_DT_MOM FROM WT_WHERE) AND (SELECT TO_DT_MOM FROM WT_WHERE) 
                 UNION ALL 
                    SELECT 'DGT' AS CHNL_ID, A.*
                      FROM REVIEW_RAW.OVER_DGT_REVIEW_SENTENCE_TABLE A INNER JOIN REVIEW_RAW.OVER_DGT_REVIEW_ABNORMAL F
                        ON (A.PROD_ID = F.PROD_ID AND A.DATE = F.DATE AND A.REVIEW_ID = F.REVIEW_ID AND F.FAKE = 0)
                     WHERE A.DATE BETWEEN (SELECT FR_DT_MOM FROM WT_WHERE) AND (SELECT TO_DT_MOM FROM WT_WHERE) 
                 UNION ALL 
                    SELECT 'DCD' AS CHNL_ID, A.*
                      FROM REVIEW_RAW.OVER_DCD_REVIEW_SENTENCE_TABLE A INNER JOIN REVIEW_RAW.OVER_DCD_REVIEW_ABNORMAL F
                        ON (A.PROD_ID = F.PROD_ID AND A.DATE = F.DATE AND A.REVIEW_ID = F.REVIEW_ID AND F.FAKE = 0)
                     WHERE A.DATE BETWEEN (SELECT FR_DT_MOM FROM WT_WHERE) AND (SELECT TO_DT_MOM FROM WT_WHERE) 
                 UNION ALL 
                    SELECT 'DGD' AS CHNL_ID, A.*
                      FROM REVIEW_RAW.OVER_DGD_REVIEW_SENTENCE_TABLE A INNER JOIN REVIEW_RAW.OVER_DGD_REVIEW_ABNORMAL F
                        ON (A.PROD_ID = F.PROD_ID AND A.DATE = F.DATE AND A.REVIEW_ID = F.REVIEW_ID AND F.FAKE = 0)
                     WHERE A.DATE BETWEEN (SELECT FR_DT_MOM FROM WT_WHERE) AND (SELECT TO_DT_MOM FROM WT_WHERE) 
               ) A LEFT OUTER JOIN 
               WT_PROD_MOM B
            ON (A.CHNL_ID = B.CHNL_ID AND A.DATE = B.DATE AND A.REVIEW_ID = B.REVIEW_ID)
         WHERE B.BRAND = '더마펌'
      GROUP BY A.CHNL_ID
              ,B.PROD_NAME
        HAVING COUNT(*) > 100
    ), WT_REVW_RATE AS
    (
        SELECT CHNL_ID
              ,PROD_NM
              ,CASE WHEN REVW_CNT = 0 THEN 0 ELSE PSTV_CNT / REVW_CNT * 100 END AS PSTV_RATE
              ,CASE WHEN REVW_CNT = 0 THEN 0 ELSE NTRL_CNT / REVW_CNT * 100 END AS NTRL_RATE
              ,CASE WHEN REVW_CNT = 0 THEN 0 ELSE NGTV_CNT / REVW_CNT * 100 END AS NGTV_RATE
          FROM WT_REVW_SUM
     UNION ALL
        SELECT 'ALL' AS CHNL_ID
              ,PROD_NM
              ,CASE WHEN SUM(REVW_CNT) = 0 THEN 0 ELSE SUM(PSTV_CNT) / SUM(REVW_CNT) * 100 END AS PSTV_RATE
              ,CASE WHEN SUM(REVW_CNT) = 0 THEN 0 ELSE SUM(NTRL_CNT) / SUM(REVW_CNT) * 100 END AS NTRL_RATE
              ,CASE WHEN SUM(REVW_CNT) = 0 THEN 0 ELSE SUM(NGTV_CNT) / SUM(REVW_CNT) * 100 END AS NGTV_RATE
          FROM WT_REVW_SUM
      GROUP BY PROD_NM
    ), WT_REVW_RATE_MOM AS
    (
        SELECT CHNL_ID
              ,PROD_NM
              ,CASE WHEN REVW_CNT = 0 THEN 0 ELSE PSTV_CNT / REVW_CNT * 100 END AS PSTV_RATE
              ,CASE WHEN REVW_CNT = 0 THEN 0 ELSE NTRL_CNT / REVW_CNT * 100 END AS NTRL_RATE
              ,CASE WHEN REVW_CNT = 0 THEN 0 ELSE NGTV_CNT / REVW_CNT * 100 END AS NGTV_RATE
          FROM WT_REVW_SUM_MOM
     UNION ALL
        SELECT 'ALL' AS CHNL_ID
              ,PROD_NM
              ,CASE WHEN SUM(REVW_CNT) = 0 THEN 0 ELSE SUM(PSTV_CNT) / SUM(REVW_CNT) * 100 END AS PSTV_RATE
              ,CASE WHEN SUM(REVW_CNT) = 0 THEN 0 ELSE SUM(NTRL_CNT) / SUM(REVW_CNT) * 100 END AS NTRL_RATE
              ,CASE WHEN SUM(REVW_CNT) = 0 THEN 0 ELSE SUM(NGTV_CNT) / SUM(REVW_CNT) * 100 END AS NGTV_RATE
          FROM WT_REVW_SUM_MOM
      GROUP BY PROD_NM
    ), WT_REVW_COMP AS
    (
        SELECT A.CHNL_ID
              ,A.PROD_NM
              ,A.PSTV_RATE - B.PSTV_RATE AS PSTV_CHNG
              ,A.NGTV_RATE - B.NGTV_RATE AS NGTV_CHNG
          FROM WT_REVW_RATE A INNER JOIN WT_REVW_RATE_MOM B 
            ON (A.CHNL_ID = B.CHNL_ID AND A.PROD_NM = B.PROD_NM)
    ), WT_PSTV_RANK AS
    (
        SELECT CHNL_ID
              ,PROD_NM
              ,PSTV_CHNG
              ,NGTV_CHNG
              ,ROW_NUMBER() OVER(PARTITION BY CHNL_ID ORDER BY PSTV_CHNG DESC, PROD_NM) AS PSTV_RANK
              ,ROW_NUMBER() OVER(PARTITION BY CHNL_ID ORDER BY NGTV_CHNG DESC, PROD_NM) AS NGTV_RANK
          FROM WT_REVW_COMP
    ), WT_BASE AS
    (
        SELECT A.SORT_KEY
              ,A.CHNL_ID
              ,A.REVW_RANK
              ,B.PROD_NM AS PSTV_PROD_NM
              ,C.PROD_NM AS NGTV_PROD_NM
              ,B.PSTV_CHNG
              ,C.NGTV_CHNG
              ,B.PSTV_RANK
              ,C.NGTV_RANK
              ,(SELECT PSNG_TYPE FROM WT_WHERE) AS PSNG_TYPE
          FROM WT_COPY_CHNL A LEFT OUTER JOIN WT_PSTV_RANK B ON (A.CHNL_ID = B.CHNL_ID AND A.REVW_RANK = B.PSTV_RANK)
                              LEFT OUTER JOIN WT_PSTV_RANK C ON (A.CHNL_ID = C.CHNL_ID AND A.REVW_RANK = C.NGTV_RANK)
    )
    SELECT REVW_RANK  /* 순위 1~5 */
          ,MAX(     CASE WHEN CHNL_ID = 'ALL' THEN CASE WHEN PSNG_TYPE = 'PSTV' THEN PSTV_PROD_NM ELSE NGTV_PROD_NM END END                  ) AS ALL_PROD_NM  /* 전체 채널     - 변화 Top5 제품명 */
          ,MAX(     CASE WHEN CHNL_ID = 'DGT' THEN CASE WHEN PSNG_TYPE = 'PSTV' THEN PSTV_PROD_NM ELSE NGTV_PROD_NM END END                  ) AS DGT_PROD_NM  /* 티몰 글로벌   - 변화 Top5 제품명 */
          ,MAX(     CASE WHEN CHNL_ID = 'DCT' THEN CASE WHEN PSNG_TYPE = 'PSTV' THEN PSTV_PROD_NM ELSE NGTV_PROD_NM END END                  ) AS DCT_PROD_NM  /* 티몰 내륙     - 변화 Top5 제품명 */
          ,MAX(     CASE WHEN CHNL_ID = 'DGD' THEN CASE WHEN PSNG_TYPE = 'PSTV' THEN PSTV_PROD_NM ELSE NGTV_PROD_NM END END                  ) AS DGD_PROD_NM  /* 도우인 글로벌 - 변화 Top5 제품명 */
          ,MAX(     CASE WHEN CHNL_ID = 'DCD' THEN CASE WHEN PSNG_TYPE = 'PSTV' THEN PSTV_PROD_NM ELSE NGTV_PROD_NM END END                  ) AS DCD_PROD_NM  /* 도우인 내륙   - 변화 Top5 제품명 */
          ,MAX(CAST(CASE WHEN CHNL_ID = 'ALL' THEN CASE WHEN PSNG_TYPE = 'PSTV' THEN PSTV_CHNG    ELSE NGTV_CHNG    END END AS DECIMAL(20,2))) AS DGT_RATE     /* 전체 채널     - 변화 Top5 제품명 */
          ,MAX(CAST(CASE WHEN CHNL_ID = 'DGT' THEN CASE WHEN PSNG_TYPE = 'PSTV' THEN PSTV_CHNG    ELSE NGTV_CHNG    END END AS DECIMAL(20,2))) AS DGT_RATE     /* 티몰 글로벌   - 변화 Top5 제품명 */
          ,MAX(CAST(CASE WHEN CHNL_ID = 'DCT' THEN CASE WHEN PSNG_TYPE = 'PSTV' THEN PSTV_CHNG    ELSE NGTV_CHNG    END END AS DECIMAL(20,2))) AS DCT_RATE     /* 티몰 내륙     - 변화 Top5 제품명 */
          ,MAX(CAST(CASE WHEN CHNL_ID = 'DGD' THEN CASE WHEN PSNG_TYPE = 'PSTV' THEN PSTV_CHNG    ELSE NGTV_CHNG    END END AS DECIMAL(20,2))) AS DGD_RATE     /* 도우인 글로벌 - 변화 Top5 제품명 */
          ,MAX(CAST(CASE WHEN CHNL_ID = 'DCD' THEN CASE WHEN PSNG_TYPE = 'PSTV' THEN PSTV_CHNG    ELSE NGTV_CHNG    END END AS DECIMAL(20,2))) AS DCD_RATE     /* 도우인 내륙   - 변화 Top5 제품명 */
      FROM WT_BASE
  GROUP BY REVW_RANK
  ORDER BY REVW_RANK